function stage_vars_structure = variables(stage)
stage_vars_structure = OclStructure();
stage_vars_structure.addRepeated({'states','integrator','controls','parameters','h'}, ...
  {stage.states, ...
  stage.integrator.vars, ...
  stage.controls, ...
  stage.parameters, ...
  OclMatrix([1,1])}, length(stage.H_norm));
stage_vars_structure.add('states', stage.states);
stage_vars_structure.add('parameters', stage.parameters);
