num_masses = 4;

stage = ocl.Stage( ...
    10, ...
    @(h) ocl.examples.linear_mass_spring.vars(h,num_masses), ...
    @(h,x,z,u,p) ocl.examples.linear_mass_spring.dae(h,x,u), ...
    @(h,x,z,u,p) ocl.examples.linear_mass_spring.pathcosts(h,x,u), ...
    @(h,k,K,x,p) ocl.examples.linear_mass_spring.gridcosts(h,k,K,x), ...
    'N', 3, 'd', 2);
                
solver = OclSolver({stage}, {});

